version: "3.7"

services:
    php:
        build:
            args:
                user: ${APP_USER}
                uid: 1000
            context: ../
            dockerfile: ./docker-compose/php/Dockerfile
        # image: docker_lemp
        # container_name: "${APP_NAME}-php"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
        # networks:
        #     - docker_lemp

    mysql:
        image: mysql:5.7
        # container_name: docker_lemp-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE} # docker fetches these from .env file in same dir as docker-compose.yml file
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d  #mysql image will automatically import .sql files placed in the /docker-entrypoint-initdb.d directory
            # - docker_lemp_mysql:/var/lib/mysql
        ports:
            - 3307:3306
        # networks:
        #     - docker_lemp

    nginx:
        image: nginx:1.17-alpine
        # container_name: docker_lemp-nginx
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
        # networks:
        #     - docker_lemp

# networks:
#     docker_lemp:
#         driver: bridge

# volumes:
#     docker_lemp_mysql: